services:
  mongodb:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    expose:
      - "27017"
  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./src/:/usr/src/app
