services:
  mongodb:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    expose:
      - "27017"
  server:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      - mongodb
